name: "[3.0] Onboard AWS Account to S3 Bucket"

run-name: "[3.0] Onboard AWS Account to S3 Bucket (Account ID: ${{ inputs.accountID }})"

on:
  workflow_dispatch:
    inputs:
      accountID:
        description: "AWS Account ID to grant access"
        required: true
        type: string
      bucketNameVeleroBackup:
        description: "S3 Bucket Name for Velero Backup"
        required: true
        type: string
        default: "velero-backup-kubernetes-aws-d89fgh"
      bucketNameTFInput:
        description: "S3 Bucket Name for Terraform Input"
        required: true
        type: string
        default: "terragrunt-input"
      region:
        description: "AWS Region"
        required: true
        type: string
        default: "us-east-1"

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.ADMIN_AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.ADMIN_AWS_SECRET_KEY }}

  ACCOUNT_ID: ${{ inputs.accountID }}
  BUCKET_NAME_VELERO_BACKUP: ${{ inputs.bucketNameVeleroBackup }}
  BUCKET_NAME_TF_INPUT: ${{ inputs.bucketNameTFInput }}
  REGION: ${{ inputs.region }}

jobs:
  onboard-account-velero-backup-bucket:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Add account access to Velero backup bucket
        run: |
          BUCKET_NAME="$BUCKET_NAME_VELERO_BACKUP" \
            bash ./script/3.onboarding-account-to-bucket/grant-access-to-root-buckets.sh

  onboard-account-tf-input-bucket:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Add account access to Terraform input bucket
        run: |
          BUCKET_NAME="$BUCKET_NAME_TF_INPUT" \
            bash ./script/3.onboarding-account-to-bucket/grant-access-to-root-buckets.sh
